# all fields are required, make a copy called config.yml
itemspath: . # path to videos to choose from
completepath: ./completed # path to move videos to after completion

log: true # whether or not to log
logfilepath: . # the path to the folder where the logfile will be stored
logfilename: randomise.log # the name of the logfile

stats: false # whether to generate stats file
statlocation: ./stats.yml # where to place stats results. needs path to filename